version: '3.8'

services:
  # Nginx service for serving static files
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: crm-nginx
    restart: unless-stopped
    ports:
      - "3000:80"  # Map container port 80 to host port 3000
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=https://esmboovriahdhtvvxgzn.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbWJvb3ZyaWFoZGh0dnZ4Z3puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzAwMTgsImV4cCI6MjA2MDMwNjAxOH0.8t1o1yk8ozklE5ltv3mNV7LHKnKZe9kdNzFTd29klIA
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - crm-network-nginx
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/crm/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  crm-network-nginx:
    driver: bridge