version: '3.8'

services:
  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: myagentview-crm:local
    container_name: crm-app-local
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=crm_db
      - POSTGRES_USER=crm_user
      - POSTGRES_PASSWORD=localpassword
      - JWT_SECRET=local_jwt_secret
      - BASE_URL=http://localhost:3000/crm
      - VITE_SUPABASE_URL=https://esmboovriahdhtvvxgzn.supabase.co
      - VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbWJvb3ZyaWFoZGh0dnZ4Z3puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzAwMTgsImV4cCI6MjA2MDMwNjAxOH0.8t1o1yk8ozklE5ltv3mNV7LHKnKZe9kdNzFTd29klIA
      - VITE_SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbWJvb3ZyaWFoZGh0dnZ4Z3puIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDczMDAxOCwiZXhwIjoyMDYwMzA2MDE4fQ.ba6BXQqd0_NpYEKIF_qUxHuOjNJKXO_-AOnZmHL4AxA
    volumes:
      - ./logs:/app/logs
    networks:
      - crm-network-local
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/crm/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Database service
  db:
    image: postgres:15-alpine
    container_name: crm-db-local
    restart: unless-stopped
    environment:
      - POSTGRES_DB=crm_db
      - POSTGRES_USER=crm_user
      - POSTGRES_PASSWORD=localpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data-local:/var/lib/postgresql/data
      - ./supabase-export/create_tables.sql:/docker-entrypoint-initdb.d/01-create_tables.sql
      - ./supabase-export/insert_data.sql:/docker-entrypoint-initdb.d/02-insert_data.sql
      - ./setup-db-permissions.sql:/docker-entrypoint-initdb.d/03-setup-permissions.sql
    ports:
      - "5432:5432"
    networks:
      - crm-network-local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-data-local:
    driver: local

networks:
  crm-network-local:
    driver: bridge