@echo off
echo Stopping existing containers...
docker-compose down

echo Copying fixed Dockerfile...
copy Dockerfile.fixed Dockerfile

echo Rebuilding Docker image with path-to-regexp fix...
docker-compose build

echo Starting containers with fixed configuration...
docker-compose up -d

echo Showing container logs (press Ctrl+C to exit)...
docker-compose logs -f
